version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    cap_add:
      - NET_ADMIN
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`${SERVER_ADDRESS}`)
      - traefik.http.routers.pihole.entrypoints=https
      - traefik.http.services.pihole.loadbalancer.server.port=80
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: "UTC"
      VIRTUAL_HOST: "${SERVER_ADDRESS}"
      PROXY_LOCATION: "${SERVER_ADDRESS}"
      WEBPASSWORD: "${ADMIN_PASSWORD}"
    networks:
      - dns
      - traefik
    volumes:
      - "./data/pihole:/etc/pihole"
      - "./data/dnsmasq.d:/etc/dnsmasq.d"

networks:
  dns:
    external: true
  traefik:
    external: true
