version: "3.7"

services:
  uptime:
    image: louislam/uptime-kuma:1
    container_name: uptime
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime.rule=Host(`${SERVER_ADDRESS}`)
      - traefik.http.routers.uptime.entrypoints=https
      - traefik.http.services.uptime.loadbalancer.server.port=3001
    dns:
      - 10.42.10.1
    networks:
      - traefik
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    external: true
